// 6 10 11 14 20 21 23 24 33 36 37 38 40 41 42 45
export const dummy = [
	{ id: 12, country:'Algeria',
		DPI: { value: 0.548, rank: 9},
		EDU: { value: 0.468, rank: 5 },
		INFRA: { value: 0.528, rank: 7 },
		BUS: { value: 0.524, rank: 23},
		ECON: { value: 0.689, rank: 4},
		REG: { value: 0.659, rank: 11},
		desc: `Algeria is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 1, country:'Angola',
		DPI: { value: 0.369, rank: 34},
		EDU: { value: 0.240, rank: 38 },
		INFRA: { value: 0.349, rank: 26 },
		BUS: { value: 0.390, rank: 36},
		ECON: { value: 0.473, rank: 32},
		REG: { value: 0.520, rank: 24},
		desc: `Angola is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 3, country:'Benin',
		DPI: { value: 0.450, rank: 19},
		EDU: { value: 0.359, rank: 23 },
		INFRA: { value: 0.322, rank: 28 },
		BUS: { value: 0.531, rank: 22},
		ECON: { value: 0.554, rank: 22},
		REG: { value: 0.621, rank: 14},
		desc: `Benin is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 5, country:'Botswana',
		DPI: { value: 0.558, rank: 7},
		EDU: { value: 0.441, rank: 9 },
		INFRA: { value: 0.474, rank: 11 },
		BUS: { value: 0.600, rank: 9},
		ECON: { value: 0.696, rank: 3},
		REG: { value: 0.736, rank: 2},
		desc: `Botswana is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 4, country:'Burkina Faso',
		DPI: { value: 0.420, rank: 27},
		EDU: { value: 0.282, rank: 36 },
		INFRA: { value: 0.305, rank: 32 },
		BUS: { value: 0.507, rank: 26},
		ECON: { value: 0.570, rank: 16},
		REG: { value: 0.602, rank: 17},
		desc: `Burkina Faso is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 2, country:'Burundi',
		DPI: { value: 0.347, rank: 36},
		EDU: { value: 0.305, rank: 32 },
		INFRA: { value: 0.280, rank: 35 },
		BUS: { value: 0.503, rank: 28},
		ECON: { value: 0.422, rank: 36},
		REG: { value: 0.178, rank: 37},
		desc: `Burundi is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 8, country:'Cameroon',
		DPI: { value: 0.418, rank: 28},
		EDU: { value: 0.393, rank: 13 },
		INFRA: { value: 0.350, rank: 25 },
		BUS: { value: 0.493, rank: 32},
		ECON: { value: 0.607, rank: 11},
		REG: { value: 0.270, rank: 29},
		desc: `Cameroon is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: '', country:'Cape Verde',
		DPI: { value: 0.485, rank: 16},
		EDU: { value: 0.390, rank: 14 },
		INFRA: { value: 0.495, rank: 10 },
		BUS: { value: 0.495, rank: 30},
		ECON: { value: 0.438, rank: 34},
		REG: { value: 0.686, rank: 6},
		desc: `Cape Verde is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 44, country:'Chad',
		DPI: { value: 0.323, rank: 37},
		EDU: { value: 0.259, rank: 37 },
		INFRA: { value: 0.181, rank: 38 },
		BUS: { value: 0.333, rank: 38},
		ECON: { value: 0.561, rank: 20},
		REG: { value: 0.475, rank: 25},
		desc: `Chad is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 9, country:'Dem. Rep. Congo',
		DPI: { value: 0.299, rank: 38},
		EDU: { value: 0.302, rank: 34 },
		INFRA: { value: 0.248, rank: 37 },
		BUS: { value: 0.384, rank: 37},
		ECON: { value: 0.374, rank: 38},
		REG: { value: 0.153, rank: 38},
		desc: `Dem. Rep. Congo is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 7, country:`Côte d'Ivoire`,
		DPI: { value: 0.491, rank: 14},
		EDU: { value: 0.357, rank: 24 },
		INFRA: { value: 0.391, rank: 19 },
		BUS: { value: 0.592, rank: 10},
		ECON: { value: 0.617, rank: 9},
		REG: { value: 0.637, rank: 13},
		desc: `Côte d'Ivoire is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 13, country:'Egypt',
		DPI: { value: 0.553, rank: 8},
		EDU: { value: 0.469, rank: 4 },
		INFRA: { value: 0.542, rank: 6 },
		BUS: { value: 0.581, rank: 12},
		ECON: { value: 0.592, rank: 14},
		REG: { value: 0.651, rank: 12},
		desc: `Egypt is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 43, country:'Swaziland',
		DPI: { value: 0.433, rank: 24},
		EDU: { value: 0.386, rank: 15 },
		INFRA: { value: 0.417, rank: 15 },
		BUS: { value: 0.551, rank: 17},
		ECON: { value: 0.494, rank: 30},
		REG: { value: 0.261, rank: 32},
		desc: `Swaziland is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 15, country:'Ethiopia',
		DPI: { value: 0.380, rank: 33},
		EDU: { value: 0.304, rank: 33 },
		INFRA: { value: 0.328, rank: 27 },
		BUS: { value: 0.467, rank: 33},
		ECON: { value: 0.593, rank: 13},
		REG: { value: 0.252, rank: 33},
		desc: `Ethiopia is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 16, country:'Gabon',
		DPI: { value: 0.479, rank: 17},
		EDU: { value: 0.401, rank: 12 },
		INFRA: { value: 0.467, rank: 12 },
		BUS: { value: 0.457, rank: 34},
		ECON: { value: 0.564, rank: 19},
		REG: { value: 0.621, rank: 15},
		desc: `Gabon is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 19, country:'Gambia',
		DPI: { value: 0.400, rank: 30},
		EDU: { value: 0.378, rank: 18 },
		INFRA: { value: 0.363, rank: 22 },
		BUS: { value: 0.507, rank: 27},
		ECON: { value: 0.430, rank: 35},
		REG: { value: 0.275, rank: 28},
		desc: `Gambia is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 17, country:'Ghana',
		DPI: { value: 0.530, rank: 10},
		EDU: { value: 0.426, rank: 10 },
		INFRA: { value: 0.499, rank: 9 },
		BUS: { value: 0.571, rank: 15},
		ECON: { value: 0.569, rank: 17},
		REG: { value: 0.680, rank: 8},
		desc: `Ghana is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 18, country:'Guinea',
		DPI: { value: 0.438, rank: 22},
		EDU: { value: 0.359, rank: 21 },
		INFRA: { value: 0.311, rank: 30 },
		BUS: { value: 0.538, rank: 21},
		ECON: { value: 0.511, rank: 28},
		REG: { value: 0.574, rank: 19},
		desc: `Guinea is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 22, country:'Kenya',
		DPI: { value: 0.560, rank: 6},
		EDU: { value: 0.463, rank: 6 },
		INFRA: { value: 0.448, rank: 14 },
		BUS: { value: 0.686, rank: 3},
		ECON: { value: 0.623, rank: 8},
		REG: { value: 0.664, rank: 10},
		desc: `Kenya is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 25, country:'Lesotho',
		DPI: { value: 0.447, rank: 21},
		EDU: { value: 0.351, rank: 26 },
		INFRA: { value: 0.354, rank: 24 },
		BUS: { value: 0.548, rank: 19},
		ECON: { value: 0.493, rank: 31},
		REG: { value: 0.579, rank: 18},
		desc: `Lesotho is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 27, country:'Madagascar',
		DPI: { value: 0.405, rank: 29},
		EDU: { value: 0.319, rank: 29 },
		INFRA: { value: 0.270, rank: 36 },
		BUS: { value: 0.495, rank: 31},
		ECON: { value: 0.548, rank: 23},
		REG: { value: 0.522, rank: 23},
		desc: `Madagascar is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 31, country:'Malawi',
		DPI: { value: 0.385, rank: 32},
		EDU: { value: 0.326, rank: 28 },
		INFRA: { value: 0.293, rank: 34 },
		BUS: { value: 0.549, rank: 18},
		ECON: { value: 0.502, rank: 29},
		REG: { value: 0.242, rank: 34},
		desc: `Malawi is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 28, country:'Mali',
		DPI: { value: 0.427, rank: 25},
		EDU: { value: 0.309, rank: 30 },
		INFRA: { value: 0.319, rank: 29 },
		BUS: { value: 0.524, rank: 24},
		ECON: { value: 0.574, rank: 15},
		REG: { value: 0.539, rank: 20},
		desc: `Mali is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 30, country:'Mauritania',
		DPI: { value: 0.396, rank: 31},
		EDU: { value: 0.306, rank: 31 },
		INFRA: { value: 0.306, rank: 31 },
		BUS: { value: 0.450, rank: 35},
		ECON: { value: 0.515, rank: 27},
		REG: { value: 0.530, rank: 21},
		desc: `Mauritania is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: '', country:'Mauritius',
		DPI: { value: 0.656, rank: 1},
		EDU: { value: 0.494, rank: 3 },
		INFRA: { value: 0.680, rank: 1 },
		BUS: { value: 0.738, rank: 1},
		ECON: { value: 0.633, rank: 6},
		REG: { value: 0.793, rank: 1},
		desc: `Mauritius is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 26, country:'Morocco',
		DPI: { value: 0.593, rank: 4},
		EDU: { value: 0.419, rank: 11 },
		INFRA: { value: 0.569, rank: 5 },
		BUS: { value: 0.666, rank: 4},
		ECON: { value: 0.753, rank: 2},
		REG: { value: 0.684, rank: 7},
		desc: `Morocco is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 29, country:'Mozambique',
		DPI: { value: 0.353, rank: 35},
		EDU: { value: 0.289, rank: 35 },
		INFRA: { value: 0.301, rank: 33 },
		BUS: { value: 0.509, rank: 25},
		ECON: { value: 0.417, rank: 37},
		REG: { value: 0.207, rank: 35},
		desc: `Mozambique is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 32, country:'Namibia',
		DPI: { value: 0.498, rank: 11},
		EDU: { value: 0.451, rank: 8 },
		INFRA: { value: 0.509, rank: 8 },
		BUS: { value: 0.563, rank: 16},
		ECON: { value: 0.545, rank: 25},
		REG: { value: 0.391, rank: 26},
		desc: `Namibia is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 34, country:'Nigeria',
		DPI: { value: 0.435, rank: 23},
		EDU: { value: 0.362, rank: 20 },
		INFRA: { value: 0.370, rank: 21 },
		BUS: { value: 0.577, rank: 13},
		ECON: { value: 0.657, rank: 5},
		REG: { value: 0.205, rank: 36},
		desc: `Nigeria is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 35, country:'Rwanda',
		DPI: { value: 0.494, rank: 13},
		EDU: { value: 0.355, rank: 25 },
		INFRA: { value: 0.452, rank: 13 },
		BUS: { value: 0.711, rank: 2},
		ECON: { value: 0.539, rank: 26},
		REG: { value: 0.382, rank: 27},
		desc: `Rwanda is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 39, country:'Senegal',
		DPI: { value: 0.497, rank: 12},
		EDU: { value: 0.365, rank: 19 },
		INFRA: { value: 0.407, rank: 16 },
		BUS: { value: 0.575, rank: 14},
		ECON: { value: 0.565, rank: 18},
		REG: { value: 0.716, rank: 4},
		desc: `Senegal is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: '', country:'Seychelles',
		DPI: { value: 0.600, rank: 3},
		EDU: { value: 0.589, rank: 1 },
		INFRA: { value: 0.612, rank: 3 },
		BUS: { value: 0.616, rank: 8},
		ECON: { value: 0.461, rank: 33},
		REG: { value: 0.707, rank: 5},
		desc: `Seychelles is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 49, country:'South Africa',
		DPI: { value: 0.632, rank: 2},
		EDU: { value: 0.517, rank: 2 },
		INFRA: { value: 0.613, rank: 2 },
		BUS: { value: 0.645, rank: 5},
		ECON: { value: 0.785, rank: 1},
		REG: { value: 0.722, rank: 3},
		desc: `South Africa is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 47, country:'Tanzania',
		DPI: { value: 0.422, rank: 26},
		EDU: { value: 0.342, rank: 27 },
		INFRA: { value: 0.359, rank: 23 },
		BUS: { value: 0.539, rank: 20},
		ECON: { value: 0.633, rank: 7},
		REG: { value: 0.265, rank: 30},
		desc: `Tanzania is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 46, country:'Tunisia',
		DPI: { value: 0.581, rank: 5},
		EDU: { value: 0.461, rank: 7 },
		INFRA: { value: 0.589, rank: 4 },
		BUS: { value: 0.639, rank: 6},
		ECON: { value: 0.596, rank: 12},
		REG: { value: 0.675, rank: 9},
		desc: `Tunisia is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 48, country:'Uganda',
		DPI: { value: 0.487, rank: 15},
		EDU: { value: 0.359, rank: 22 },
		INFRA: { value: 0.394, rank: 18 },
		BUS: { value: 0.582, rank: 11},
		ECON: { value: 0.608, rank: 10},
		REG: { value: 0.616, rank: 16},
		desc: `Uganda is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 50, country:'Zambia',
		DPI: { value: 0.449, rank: 20},
		EDU: { value: 0.381, rank: 16 },
		INFRA: { value: 0.395, rank: 17 },
		BUS: { value: 0.617, rank: 7},
		ECON: { value: 0.548, rank: 24},
		REG: { value: 0.263, rank: 31},
		desc: `Zambia is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
	{ id: 51, country:'Zimbabwe',
		DPI: { value: 0.450, rank: 18},
		EDU: { value: 0.380, rank: 17 },
		INFRA: { value: 0.381, rank: 20 },
		BUS: { value: 0.502, rank: 29},
		ECON: { value: 0.554, rank: 21},
		REG: { value: 0.523, rank: 22},
		desc: `Zimbabwe is a country add amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.`
		},
];

const lorem = 'Id amet laoreet cursus mollis donec. Sed tellus ut justo ultrices nibh urna. Amet blandit odio vestibulum eget sollicitudin. In sagittis sed donec eget. In consequat, a hendrerit turpis massa. Sed justo, nibh sed morbi malesuada. Molestie molestie amet, purus id.'

export const text = [
		{ name: 'DPI', text: `DPI ${lorem}`},
		{ name: 'EDU', text: `EDU ${lorem}`},
		{ name: 'INFRA', text: `INFRA ${lorem}`},
		{ name: 'BUS', text: `BUS ${lorem}`},
		{ name: 'ECON', text: `ECON ${lorem}`},
		{ name: 'REG', text: `REG ${lorem}`}	
]
